### ISSUE TITLE
Assertions generator doesn't generate for inner classes

### ISSUE THREAD

**Issue by baztian** [joel-costigliola/assertj-examples#19]
I did not manage to generate assertions for public static inner classes. I have a lot of these inner classes as they are generated jaxb.

**Comment by joel-costigliola** [comment]
no feedback, closing the issue.

**Comment by Uriziel47** [comment]
Maybe the problem arised with the use of the CLI launcher `*.cli.AssertionGeneratorLauncher` (e.g. in a build script) and its option `-H` for hierarchical generation. Unfortunately with this option no inner classes' assertions will be generate automatically. You have to explicitly provide these inner classes as arguments `package.OuterClass$InnerClass` then the assertions will be generated.
