### ISSUE TITLE
Broken Examples

### ISSUE THREAD

**Issue by iexcept** [joel-costigliola/assertj-examples#24]
Steps to reproduce:

1. clone "assertj-examples"
2. go to subdir "assertions-examples"
3. run "mvn clean install"
4. observe a lot of errors

[ERROR] at com.sun.tools.javac.comp.Lower.translate(Lower.java:2371)
[ERROR] at com.sun.tools.javac.comp.Lower.visitApply(Lower.java:3069)
[ERROR] at com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java
:1465)
[ERROR] at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java
:58)
[ERROR] at com.sun.tools.javac.comp.Lower.translate(Lower.java:2371)
[ERROR] at com.sun.tools.javac.comp.Lower.visitTypeCast(Lower.java:2866)
[ERROR] at com.sun.tools.javac.tree.JCTree$JCTypeCast.accept(JCTree.java:1814)
[ERROR] at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java
:58)
[ERROR] at com.sun.tools.javac.comp.Lower.translate(Lower.java:2371)
[ERROR] at com.sun.tools.javac.comp.Lower.visitSelect(Lower.java:3840)
[ERROR] at com.sun.tools.javac.tree.JCTree$JCFieldAccess.accept(JCTree.java:1897
)
[ERROR] at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java
:58)
[ERROR] at com.sun.tools.javac.comp.Lower.translate(Lower.java:2371)
[ERROR] at com.sun.tools.javac.comp.Lower.visitApply(Lower.java:3069)
[ERROR] at com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java
:1465)
[ERROR] at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java
:58)
[ERROR] at com.sun.tools.javac.comp.Lower.translate(Lower.java:2371)
[ERROR] at com.sun.tools.javac.comp.Lower.visitTypeCast(Lower.java:2866)
[ERROR] at com.sun.tools.javac.tree.JCTree$JCTypeCast.accept(JCTree.java:1814)
[ERROR] at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java
:58)
[ERROR] at com.sun.tools.javac.comp.Lower.translate(Lower.java:2371)
[ERROR] at com.sun.tools.javac.comp.Lower.visitSelect(Lower.java:3840)
[ERROR] at com.sun.tools.javac.tree.JCTree$JCFieldAccess.accept(JCTree.java:1897
)
[ERROR] at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java
:58)
[ERROR] at com.sun.tools.javac.comp.Lower.translate(Lower.java:2371)
[ERROR] at com.sun.tools.javac.comp.Lower.visitApply(Lower.java:3069)
[ERROR] at com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java
:1465)
[ERROR] at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java
:58)
[ERROR] at com.sun.tools.javac.comp.Lower.translate(Lower.java:2371)
[ERROR] at com.sun.tools.javac.comp.Lower.visitTypeCast(Lower.java:2866)
[ERROR] at com.sun.tools.javac.tree.JCTree$JCTypeCast.accept(JCTree.java:1814)
[ERROR] at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java
:58)
[ERROR] at com.sun.tools.javac.comp.Lower.translate(Lower.java:2371)
[ERROR] at com.sun.tools.javac.comp.Lower.visitSelect(Lower.java:3840)
[ERROR] at com.sun.tools.javac.tree.JCTree$JCFieldAccess.accept(JCTree.java:1897
)
[ERROR] at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java
:58)
[ERROR] at com.sun.tools.javac.comp.Lower.translate(Lower.java:2371)
[ERROR] at com.sun.tools.javac.comp.Lower.visitApply(Lower.java:3069)
[ERROR] at com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java
:1465)
[ERROR] at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java
:58)
[ERROR] at com.sun.tools.javac.comp.Lower.translate(Lower.java:2371)
[ERROR] at com.sun.tools.javac.comp.Lower.visitTypeCast(Lower.java:2866)
[ERROR] at com.sun.tools.javac.tree.JCTree$JCTypeCast.accept(JCTree.java:1814)
[ERROR] at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java
:58)
[ERROR] at com.sun.tools.javac.comp.Lower.translate(Lower.java:2371)
[ERROR] at com.sun.tools.javac.comp.Lower.visitSelect(Lower.java:3840)
[ERROR] at com.sun.tools.javac.tree.JCTree$JCFieldAccess.accept(JCTree.java:1897
)
[ERROR] at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java
:58)
[ERROR] at com.sun.tools.javac.comp.Lower.translate(Lower.java:2371)
[ERROR] at com.sun.tools.javac.comp.Lower.visitApply(Lower.java:3069)
[ERROR] at com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java
:1465)
[ERROR] at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java
:58)
[ERROR] at com.sun.tools.javac.comp.Lower.translate(Lower.java:2371)
[ERROR] at com.sun.tools.javac.comp.Lower.visitTypeCast(Lower.java:2866)
[ERROR] at com.sun.tools.javac.tree.JCTree$JCTypeCast.accept(JCTree.java:1814)
[ERROR] at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java
:58)
[ERROR] at com.sun.tools.javac.comp.Lower.translate(Lower.java:2371)
[ERROR] at com.sun.tools.javac.comp.Lower.visitSelect(Lower.java:3840)
[ERROR] at com.sun.tools.javac.tree.JCTree$JCFieldAccess.accept(JCTree.java:1897
)
[ERROR] at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java
:58)
[ERROR] at com.sun.tools.javac.comp.Lower.translate(Lower.java:2371)
[ERROR] at com.sun.tools.javac.comp.Lower.visitApply(Lower.java:3069)
[ERROR] at com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java
:1465)
[ERROR] at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java
:58)
[ERROR] at com.sun.tools.javac.comp.Lower.translate(Lower.java:2371)
[ERROR] at com.sun.tools.javac.comp.Lower.visitTypeCast(Lower.java:2866)
[ERROR] at com.sun.tools.javac.tree.JCTree$JCTypeCast.accept(JCTree.java:1814)
[ERROR] at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java
:58)
[ERROR] at com.sun.tools.javac.comp.Lower.translate(Lower.java:2371)
[ERROR] at com.sun.tools.javac.comp.Lower.visitSelect(Lower.java:3840)
[ERROR] at com.sun.tools.javac.tree.JCTree$JCFieldAccess.accept(JCTree.java:1897
)
[ERROR] at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java
:58)
[ERROR] at com.sun.tools.javac.comp.Lower.translate(Lower.java:2371)
[ERROR] at com.sun.tools.javac.comp.Lower.visitApply(Lower.java:3069)
[ERROR] at com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java
:1465)
[ERROR] at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java
:58)
[ERROR] at com.sun.tools.javac.comp.Lower.translate(Lower.java:2371)
[ERROR] at com.sun.tools.javac.comp.Lower.visitTypeCast(Lower.java:2866)
[ERROR] at com.sun.tools.javac.tree.JCTree$JCTypeCast.accept(JCTree.java:1814)
[ERROR] at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java
:58)
[ERROR] at com.sun.tools.javac.comp.Lower.translate(Lower.java:2371)
[ERROR] at com.sun.tools.javac.comp.Lower.visitSelect(Lower.java:3840)
[ERROR] at com.sun.tools.javac.tree.JCTree$JCFieldAccess.accept(JCTree.java:1897
)
[ERROR] at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java
:58)
[ERROR] at com.sun.tools.javac.comp.Lower.translate(Lower.java:2371)
[ERROR] at com.sun.tools.javac.comp.Lower.visitApply(Lower.java:3069)
[ERROR] at com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java
:1465)
[ERROR] at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java
:58)
[ERROR] at com.sun.tools.javac.comp.Lower.translate(Lower.java:2371)
[ERROR] at com.sun.tools.javac.comp.Lower.visitTypeCast(Lower.java:2866)
[ERROR] at com.sun.tools.javac.tree.JCTree$JCTypeCast.accept(JCTree.java:1814)
[ERROR] at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java
:58)
[ERROR] at com.sun.tools.javac.comp.Lower.translate(Lower.java:2371)
[ERROR] at com.sun.tools.javac.comp.Lower.visitSelect(Lower.java:3840)
[ERROR] at com.sun.tools.javac.tree.JCTree$JCFieldAccess.accept(JCTree.java:1897
)
[ERROR] at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java
:58)
[ERROR] at com.sun.tools.javac.comp.Lower.translate(Lower.java:2371)
[ERROR] at com.sun.tools.javac.comp.Lower.visitApply(Lower.java:3069)
[ERROR] at com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java
:1465)
[ERROR] at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java
:58)
[ERROR] at com.sun.tools.javac.comp.Lower.translate(Lower.java:2371)
[ERROR] at com.sun.tools.javac.comp.Lower.visitTypeCast(Lower.java:2866)
[ERROR] at com.sun.tools.javac.tree.JCTree$JCTypeCast.accept(JCTree.java:1814)
[ERROR] at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java
:58)
[ERROR] at com.sun.tools.javac.comp.Lower.translate(Lower.java:2371)
[ERROR] at com.sun.tools.javac.comp.Lower.visitSelect(Lower.java:3840)
[ERROR] at com.sun.tools.javac.tree.JCTree$JCFieldAccess.accept(JCTree.java:1897
)
[ERROR] at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java
:58)
[ERROR] at com.sun.tools.javac.comp.Lower.translate(Lower.java:2371)
[ERROR] at com.sun.tools.javac.comp.Lower.visitApply(Lower.java:3069)
[ERROR] at com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java
:1465)
[ERROR] at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java
:58)
[ERROR] at com.sun.tools.javac.comp.Lower.translate(Lower.java:2371)
[ERROR] at com.sun.tools.javac.comp.Lower.visitTypeCast(Lower.java:2866)
[ERROR] at com.sun.tools.javac.tree.JCTree$JCTypeCast.accept(JCTree.java:1814)
[ERROR] at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java
:58)
[ERROR] at com.sun.tools.javac.comp.Lower.translate(Lower.java:2371)
[ERROR] at com.sun.tools.javac.comp.Lower.visitSelect(Lower.java:3840)
[ERROR] at com.sun.tools.javac.tree.JCTree$JCFieldAccess.accept(JCTree.java:1897
)
[ERROR] at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java
:58)
[ERROR] at com.sun.tools.javac.comp.Lower.translate(Lower.java:2371)
[ERROR] at com.sun.tools.javac.comp.Lower.visitApply(Lower.java:3069)
[ERROR] at com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java
:1465)
[ERROR] at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java
:58)
[ERROR] at com.sun.tools.javac.comp.Lower.translate(Lower.java:2371)
[ERROR] at com.sun.tools.javac.comp.Lower.visitTypeCast(Lower.java:2866)
[ERROR] at com.sun.tools.javac.tree.JCTree$JCTypeCast.accept(JCTree.java:1814)
[ERROR] at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java
:58)
[ERROR] at com.sun.tools.javac.comp.Lower.translate(Lower.java:2371)
[ERROR] at com.sun.tools.javac.comp.Lower.visitSelect(Lower.java:3840)
[ERROR] at com.sun.tools.javac.tree.JCTree$JCFieldAccess.accept(JCTree.java:1897
)
[ERROR] at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java
:58)
[ERROR] at com.sun.tools.javac.comp.Lower.translate(Lower.java:2371)
[ERROR] at com.sun.tools.javac.comp.Lower.visitApply(Lower.java:3069)
[ERROR] at com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java
:1465)
[ERROR] at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java
:58)
[ERROR] at com.sun.tools.javac.comp.Lower.translate(Lower.java:2371)
[ERROR] at com.sun.tools.javac.comp.Lower.visitTypeCast(Lower.java:2866)
[ERROR] at com.sun.tools.javac.tree.JCTree$JCTypeCast.accept(JCTree.java:1814)
[ERROR] at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java
:58)
[ERROR] at com.sun.tools.javac.comp.Lower.translate(Lower.java:2371)
[ERROR] at com.sun.tools.javac.comp.Lower.visitSelect(Lower.java:3840)
[ERROR] at com.sun.tools.javac.tree.JCTree$JCFieldAccess.accept(JCTree.java:1897
)
[ERROR] at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java
:58)
[ERROR] at com.sun.tools.javac.comp.Lower.translate(Lower.java:2371)
[ERROR] at com.sun.tools.javac.comp.Lower.visitApply(Lower.java:3069)
[ERROR] at com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java
:1465)
[ERROR] at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java
:58)
[ERROR] at com.sun.tools.javac.comp.Lower.translate(Lower.java:2371)
[ERROR] at com.sun.tools.javac.comp.Lower.visitTypeCast(Lower.java:2866)
[ERROR] at com.sun.tools.javac.tree.JCTree$JCTypeCast.accept(JCTree.java:1814)
[ERROR] at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java
:58)
[ERROR] at com.sun.tools.javac.comp.Lower.translate(Lower.java:2371)
[ERROR] at com.sun.tools.javac.comp.Lower.visitSelect(Lower.java:3840)
[ERROR] at com.sun.tools.javac.tree.JCTree$JCFieldAccess.accept(JCTree.java:1897
)
[ERROR] at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java
:58)
[ERROR] at com.sun.tools.javac.comp.Lower.translate(Lower.java:2371)
[ERROR] at com.sun.tools.javac.comp.Lower.visitApply(Lower.java:3069)
[ERROR] at com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java
:1465)
[ERROR] at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java
:58)
[ERROR] at com.sun.tools.javac.comp.Lower.translate(Lower.java:2371)
[ERROR] at com.sun.tools.javac.comp.Lower.visitTypeCast(Lower.java:2866)
[ERROR] at com.sun.tools.javac.tree.JCTree$JCTypeCast.accept(JCTree.java:1814)
[ERROR] at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java
:58)
[ERROR] at com.sun.tools.javac.comp.Lower.translate(Lower.java:2371)
[ERROR] at com.sun.tools.javac.comp.Lower.visitSelect(Lower.java:3840)
[ERROR] at com.sun.tools.javac.tree.JCTree$JCFieldAccess.accept(JCTree.java:1897
)
[ERROR] at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java
:58)
[ERROR] at com.sun.tools.javac.comp.Lower.translate(Lower.java:2371)
[ERROR] at com.sun.tools.javac.comp.Lower.visitApply(Lower.java:3069)
[ERROR] at com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java
:1465)
[ERROR] at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java
:58)
[ERROR] at com.sun.tools.javac.comp.Lower.translate(Lower.java:2371)
[ERROR] at com.sun.tools.javac.comp.Lower.visitTypeCast(Lower.java:2866)
[ERROR] at com.sun.tools.javac.tree.JCTree$JCTypeCast.accept(JCTree.java:1814)
[ERROR] at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java
:58)
[ERROR] at com.sun.tools.javac.comp.Lower.translate(Lower.java:2371)
[ERROR] at com.sun.tools.javac.comp.Lower.visitSelect(Lower.java:3840)
[ERROR] at com.sun.tools.javac.tree.JCTree$JCFieldAccess.accept(JCTree.java:1897
)
[ERROR] at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java
:58)
[ERROR] at com.sun.tools.javac.comp.Lower.translate(Lower.java:2371)
[ERROR] at com.sun.tools.javac.comp.Lower.visitApply(Lower.java:3069)
[ERROR] at com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java
:1465)
[ERROR] at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java
:58)
[ERROR] at com.sun.tools.javac.comp.Lower.translate(Lower.java:2371)
[ERROR] at com.sun.tools.javac.comp.Lower.visitTypeCast(Lower.java:2866)
[ERROR] at com.sun.tools.javac.tree.JCTree$JCTypeCast.accept(JCTree.java:1814)
[ERROR] at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java
:58)
[ERROR] at com.sun.tools.javac.comp.Lower.translate(Lower.java:2371)
[ERROR] at com.sun.tools.javac.comp.Lower.visitSelect(Lower.java:3840)
[ERROR] at com.sun.tools.javac.tree.JCTree$JCFieldAccess.accept(JCTree.java:1897
)
[ERROR] at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java
:58)
[ERROR] at com.sun.tools.javac.comp.Lower.translate(Lower.java:2371)
[ERROR] at com.sun.tools.javac.comp.Lower.visitApply(Lower.java:3069)
[ERROR] at com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java
:1465)
[ERROR] at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java
:58)
[ERROR] at com.sun.tools.javac.comp.Lower.translate(Lower.java:2371)
[ERROR] at com.sun.tools.javac.comp.Lower.visitTypeCast(Lower.java:2866)
[ERROR] at com.sun.tools.javac.tree.JCTree$JCTypeCast.accept(JCTree.java:1814)
[ERROR] at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java
:58)
[ERROR] at com.sun.tools.javac.comp.Lower.translate(Lower.java:2371)
[ERROR] at com.sun.tools.javac.comp.Lower.visitSelect(Lower.java:3840)
[ERROR] at com.sun.tools.javac.tree.JCTree$JCFieldAccess.accept(JCTree.java:1897
)
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureExc
eption

**Comment by joel-costigliola** [comment]
Hi
What version of java are you using ? (java 7+ needed)

**Comment by iexcept** [comment]
Hi Joel,
I'm trying to build `master` branch of examples using JDK 8.
```
$ mvn --version
Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T14:57:3
7+03:00)
Maven home: c:\Java\apache-maven-3.3.3
Java version: 1.8.0_51, vendor: Oracle Corporation
Java home: c:\Java\jdk1.8.0_51\jre
Default locale: en_US, platform encoding: Cp1251
OS name: "windows 7", version: "6.1", arch: "amd64", family: "dos"
```

**Comment by joel-costigliola** [comment]
I actually have a java-8 branch that works well for ... java 8, it might not be handy though if it uses SNAPSHOT dependencies

**Comment by PascalSchumacher** [comment]
I can replicate this. It works fine with java 7, I get the same error with java 8 on windows.

**Comment by PascalSchumacher** [comment]
Fixed. Thanks for reporting! :+1:
