### ISSUE TITLE
versions not up to date

### ISSUE THREAD

**Issue by PascalSchumacher** [joel-costigliola/assertj-examples#27]
The readme claims "The master branch contains examples with the latest released version of AssertJ modules", but the master branch uses `assertj-core 2.1.0` and `assertj-guava 2.0.0`.

**Comment by joel-costigliola** [comment]
Yeah this need to be fixed.
I mainly use the branch with the snapshot versions as a test safety net, but for our users we should have the master branch showing the latest capabilities of AssertJ.

**Comment by joel-costigliola** [comment]
@PascalSchumacher I have added you as a collaborator of this project.

**Comment by PascalSchumacher** [comment]
So should we merge the java-8 branch into master?

**Comment by joel-costigliola** [comment]
That's a good idea to be consistent with assertj-core naming, I will introduce a java-7 branch to showcase assertj-cre 2.x and other java 7 assertj components.

**Comment by joel-costigliola** [comment]
Done.
I might add a with-latest-snapshot-versions-java-7 branch (or java-7-snapshot maybe) to have a branch matching assertj-core 2.x SNAPSHOT.
