### ISSUE TITLE
Running examples in Intellij/Idea requires src/test/generated-assertions to be marked as a test source folder

### ISSUE THREAD

**Issue by HappyRay** [joel-costigliola/assertj-examples#36]
I tried the following version:

commit 518ca7385edafa6998c62b50ac6c996887d71ba5 (HEAD -> master, origin/master, origin/HEAD)
Author: Joel Costigliola <joel.costigliola@gmail.com>
Date:   Sun May 21 15:50:31 2017 +1200

    use assertj-core 3.8.0

in Intellij 2017.2.

Running 
org.assertj.examples.ArrayAssertionsExamples
for example in the IDE
caused compilation errors.

After I marked  src/test/generated-assertions as a test source folder, it started to work.

The README says:
"In your IDE, add src/test/generated-assertions to the project java sources if you IDE shows errors/missing classes. This folder is where custom assertions classes are generated, it shows what you have with the maven assertions generator plugin."

Is this instruction correct?

**Comment by joel-costigliola** [comment]
have you run `mvn clean install` to generate the sources before importing the project ?

**Comment by HappyRay** [comment]
Yes.

Sample compilation errors:

assertj-examples/assertions-examples/src/test/generated-assertions/org/assertj/examples/data/bug27/AbstractMyModelClassMyBeanAssert.java
Error:(3, 28) java: package org.assertj.core.api does not exist
Error:(8, 145) java: cannot find symbol
  symbol: class AbstractAssert
examples/assertj-examples/assertions-examples/src/test/generated-assertions/org/assertj/examples/data/AbstractMansionAssert.java
Error:(3, 28) java: package org.assertj.core.api does not exist
Error:(8, 111) java: cannot find symbol
  symbol: class AbstractAssert
examples/assertj-examples/assertions-examples/src/test/generated-assertions/org/assertj/examples/data/AbstractBasketBallPlayerAssert.java
Error:(3, 28) java: package org.assertj.core.api does not exist
Error:(4, 28) java: package org.assertj.core.api does not exist
Error:(5, 33) java: package org.assertj.core.internal does not exist
Error:(6, 29) java: package org.assertj.core.util does not exist
Error:(11, 138) java: cannot find symbol
  symbol: class AbstractAssert
examples/assertj-examples/assertions-examples/src/test/generated-assertions/org/assertj/examples/data/AbstractTeamAssert.java

**Comment by joel-costigliola** [comment]
what is the result of `mvn clean install` ?

**Comment by HappyRay** [comment]
In IDE.

mvn clean install worked fine.

**Comment by joel-costigliola** [comment]
Then you haven't imported the project correctly in your IDE, from what I see assertj-core dependency is missing is your IDE project.

**Comment by HappyRay** [comment]
I imported the project by loading the pom.xml file as a project into the intellij IDE. Is there a better/correct way to import the project?

**Comment by joel-costigliola** [comment]
I have reproduced the problem, it seems that Intellij Idea is not importing the project correctly, it sets `test/generated-assertions` as a source folder (in blue) instead of a test (in green), if you change it to a test folder in the module settings all will compile fine.

**Comment by HappyRay** [comment]
Thanks. That's what I discovered too. See the issue description.
I did a google search and couldn't find an answer. 
I hope by filing an issue here at least others who run into the same problem can hopefully find a solution/workaround.

**Comment by joel-costigliola** [comment]
I will update the documentation but it is an Intellij Idea problem.

Thanks for reporting this.

**Comment by HappyRay** [comment]
I understand.

Thanks!

**Comment by joel-costigliola** [comment]
I have just updated the [README.md](https://github.com/joel-costigliola/assertj-examples/blob/master/README.md), can you tell me if this clear enough ?

**Comment by HappyRay** [comment]
Yes, it is clear. 

Thanks!

**Comment by PrasadNutalapati** [comment]
I am having almost the same problem with Eclipse. I am getting
package org.assertj.core.api does not exist 
even though I am specifying in my pom, version 3.6.2 while using JDK 1.8.
How to overcome it ?

**Comment by joel-costigliola** [comment]
Try a maven refresh project from eclipse.

**Comment by joel-costigliola** [comment]
@PrasadNutalapati  can you show the pom.xml ? 
Please check is Basil's answer in https://stackoverflow.com/questions/54393445/cannot-resolve-symbol-assertions-error-message-when-trying-to-use-assertj addresses your issue.

**Comment by PrasadNutalapati** [comment]
I overcome this problem by removing the <scope>test</scope> for the dependency assertJ. This made the code compile and run, but the tests are not running, because the classes which invoke the assertions are in src/main/java folder.
Is there a scope which is super set of 'test' ?
