### ISSUE TITLE
Library for assertj-swing-aut Missing?

### ISSUE THREAD

**Issue by SoumyaBillava** [joel-costigliola/assertj-examples#41]
Hi,

I have same environment set up in my desktop but when I add dependency for assertj-swing-aut, It's not available
     <dependency>
      <groupId>org.assertj</groupId>
      <artifactId>assertj-swing-aut</artifactId>
      <version>1.0.0-SNAPSHOT</version>
      <scope>test</scope>
    </dependency>

Compilation error :Missing artifiact

**Comment by joel-costigliola** [comment]
@SoumyaBillava what are you trying to achieve ?

**Comment by SoumyaBillava** [comment]
I am trying to automate a desktop swing application. To start with, I want to open the applicationusing below code
public void setUp() {
  SimpleCopyApplication frame = GuiActionRunner.execute(() -> new SimpleCopyApplication());
  window = new FrameFixture(frame);
  window.show(); // shows the frame to test
}
to use simpleCopyApplication, I would like to import assertj-swing-aut

**Comment by joel-costigliola** [comment]
I'm not maintaining assertj-swing (@croesch does) but I would recommend you to read http://joel-costigliola.github.io/assertj/assertj-swing-getting-started.html if you haven't done so.

**Comment by croesch** [comment]
Sorry for missing this issue :/

The `assertj-swing-aut` is not deployed in a public repository. However you can install it to your local maven repository, by cloning it and performing `mvn install`. Afterwards you can use the example AUT in your tests.

Hope that helps, if not - just reopen this issue..
