### ISSUE TITLE
Reusing the framefixture for multiple tests

### ISSUE THREAD

**Issue by eitzenbe** [joel-costigliola/assertj-examples#44]
Hi,
I really like assertJ's swing module but found it impossible 
to like instantiate the FrameFixture ONCE per class and run a few tests on the same frame fixture,
as the robot gets cleaned up after each test method. Any way of achieving this ?

br
Thomas

**Comment by eitzenbe** [comment]
Answering my own question ;)

package org.et.mmplayer;

import org.assertj.swing.core.BasicRobot;
import org.assertj.swing.core.Robot;
import org.assertj.swing.dependency.jsr305.Nonnull;
import org.assertj.swing.edt.FailOnThreadViolationRepaintManager;
import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;

public class BasicSwingTestcase {
    private static Robot robo;

    public BasicSwingTestcase() {
    }

    @BeforeClass
    public static final void setUpOnce() {
      if (robo == null) {
        robo = BasicRobot.robotWithNewAwtHierarchy();
      }
      FailOnThreadViolationRepaintManager.install();
    }

    @Before
    public final void setUp() {
      this.onSetUp();
    }

    protected void onSetUp() {};

    @AfterClass
    public static final void tearDownOnce() {
      robo.cleanUp();
      FailOnThreadViolationRepaintManager.uninstall();
    }

    @After
    public final void tearDown() {
        this.onTearDown();
    }

    protected void onTearDown() {
    }

  /**
   * @return this test's {@link Robot}
   */
  protected static final @Nonnull Robot robot() {
    return robo;
  }

}

Easier then expected

**Comment by PascalSchumacher** [comment]
I'm closing this because assertj-swing issues should be reported at: https://github.com/joel-costigliola/assertj-swing/issues
