### ISSUE TITLE
Launching a JNLP file .Can I launch a JNLP file and test

### ISSUE THREAD

**Issue by mrif0393** [joel-costigliola/assertj-examples#45]

**Comment by mrif0393** [comment]
@croesch Can we launch JNLP file and tests,I have tool to inspect the swing elements.

**Comment by croesch** [comment]
You can test an jnlp application but IMO not via web start.

An JNLP file references an application and you should be able to start that application via AssertJ Swing through the `ApplicationLauncher` documented [here](https://joel-costigliola.github.io/assertj/assertj-swing-launch.html).

This should help you. Please note that web start is not part of Java anymore.. so your application has to find alternative starting technologies.

Just reopen, if my answer doesn't help..

**Comment by mrif0393** [comment]
Basically this is to test oracle forms application.I have .JNLP file with me and I can open it using command .
javaws xx.jnlp 
I am not sure how to open it with ApplicationLauncher any code snippets.

**Comment by croesch** [comment]
Have a look inside the jnlp file, you should be able to identify the class with the main method. In doubt read the [JNLP File Syntax](https://docs.oracle.com/javase/8/docs/technotes/guides/javaws/developersguide/syntax.html) which states that you should see an element `application-desc` with the attribute `main-class`.

That's the one you're looking for. Given that check the [link I posted above](https://joel-costigliola.github.io/assertj/assertj-swing-launch.html) and insert the main class in the example code of the ApplicationLauncher.

**Comment by mrif0393** [comment]
Thanks again,I dont have an application-desc section in my JNLP.   This is my JNLP looks like.I have section called applet desc.

`<?xml version="1.0" encoding="UTF-8"?>
<jnlp spec="1.0"
      xmlns:jfx="http://javafx.com"
      codebase="***my app url***">
    <information>
        <title>Oracle Forms Services</title>
        <vendor>Oracle Corporation</vendor>
        <homepage href="http://www.oracle.com"/>
        <description>Oracle Forms Services applet launcher.</description>
        <description kind="short">Oracle Forms Applet</description>
    </information>
    <security>
        <all-permissions/>
    </security>
    <update check="always" policy="prompt-run"/>
    <resources>
        
        <j2se version="1.7+" href="http://java.sun.com/products/autodl/j2se"/>
        <jfx:javafx-runtime version="2.2+"/>
        <jar href="/forms/java/test.jar" download="eager" main="true" />
        <extension name="Extensions" href="/forms/java/***.jnlp"/>
    </resources>
    <applet-desc 
    name="Oracle Forms"
    main-class="oracle.forms.engine.Main"
    height="1"
    width="1">
    <param name="serverURL" value="***My url**"/>
    <param name="height" value="800"/>
    <param name="width" value="1800"/>
    <param name="networkRetries" value="0"/>
    <param name="separateFrame" value="false"/>
    <param name="splashScreen"  value=""/>
    <param name="background"  value=""/>
    <param name="lookAndFeel"  value="Oracle"/>
    <param name="colorScheme"  value="swan"/>
    <param name="customColorScheme"  value=""/>
    <param name="serverApp" value=""/>
    <param name="logo" value=""/>
    <param name="imageBase" value="codebase"/>
    <param name="formsMessageListener" value=""/>
    <param name="recordFileName" value=""/>
    <param name="EndUserMonitoringEnabled" value="false"/>
    <param name="EndUserMonitoringURL" value=""/>
    <param name="heartBeat" value=""/>
    <param name="MaxEventWait" value=""/>
    <param name="allowAlertClipboard" value="true"/>
    <param name="disableValidateClipboard" value="false"/>
    <param name="enableJavascriptEvent" value="true"/>
    <param name="digitSubstitution" value="context"/>
    <param name="legacy_lifecycle" value="false"/>
    <param name="JavaScriptBlocksHeartBeat" value="false"/>
    <param name="highContrast" value="false"/>
    <param name="disableMDIScrollbars" value=""/>
    <param name="clientDPI" value=""/>
    <param name="applet_stop_timeout" value="800"/>
    <param name="guiMode" value="0"/>
    <param name="idleTimeout" value=""/>
    <param name="ssoLogoutRedirect" value=""/>
    <param name="ssoMode" value="false"/>
    <param name="ssoLogout" value="false"/>
    <param name="logoutTargetURLParamname" value=""/>
    <param name="mediaBase" value="codebase"/>
    <param name="webstartRequest" value="true"/>
    <param name="webFormsTitle" value="Oracle Fusion Middleware Forms Services Test"/>
    <param name="centerOnStartup" value=""/>
    <param name="isResizable" value=""/>
    <param name="alwaysOnTop" value=""/>
    </applet-desc>
</jnlp>`

**Comment by mrif0393** [comment]
Yes Thanks,I had a look at it earlier,So my concern is how I can launch the applet by giving the class name only.Fyi I do not have any source codes with me related to the application.I only have the JNLP file.
this is what I tried
AppletViewer viewer = AppletLauncher.applet("oracle.forms.engine.Main").start();

I can try with setting the applet properties as well but 
I see lot of properties in JNLP file apart from applet properties.How can I set them and launch it. Any tips how can I do it?

Manually what i do is i just double click the JNLP file it launches the app.

**Comment by mrif0393** [comment]
Thanks,I am a Test Engineer,I just have the JNLP file no contact with any developers.But As you said I will give a try and get back to you.

**Comment by mrif0393** [comment]
@croesch  I am getting following error when trying to launch the applet.
`Map<String, String> parameters = new HashMap<String, String>();
         parameters.put("OpenURL", "https://www.qoppa.com/files/pdfnotes/demo/serverfiles/sample02.pdf");
        parameters.put("SaveURL", "https://www.qoppa.com/files/pdfnotes/demo/serverfiles/sample02.pdf");
        parameters.put("OpenVisible", "false");
        parameters.put("java_arguments", "Xmx256m");

        AppletViewer viewer = AppletLauncher.applet("qoppa.webNotes.SaveToWeb").withParameters().start();
        FrameFixture applet = new FrameFixture(viewer).show();`

 java.lang.Error: Unexpected window shown - this window should be handled with WindowInterceptor. 
Window contents:
<window title="Applet Viewer: qoppa.webNotes.SaveToWeb">
<textBox name="status" text="Applet loaded"/>
</window>

	at org.assertj.swing.edt.GuiActionRunner.rethrowCaughtExceptionIn(GuiActionRunner.java:197)
	at org.assertj.swing.edt.GuiActionRunner.execute(GuiActionRunner.java:146)
	at org.assertj.swing.edt.GuiActionRunner.execute(GuiActionRunner.java:121)
	at org.assertj.swing.launcher.NewAppletViewerQuery.showAppletViewerWith(NewAppletViewerQuery.java:40)
	at org.assertj.swing.launcher.AppletLauncher.start(AppletLauncher.java:204)



[jPDFNotes_savetoweb.jnlp.zip](https://github.com/joel-costigliola/assertj-examples/files/2579567/jPDFNotes_savetoweb.jnlp.zip)

**Comment by croesch** [comment]
Hello @mrif0393

this looks like an application error. Do you have the full stack trace available? I suggest you ask the development department about that message..

**Comment by workmichsem** [comment]
@croesch 
Hey.
How will autotest see the application under test?

My situation is very similar to mrif0393.
The only file related to the application under test is .jnlp.
There is _<application-desc main-class = "bo.Main">_ in .jnlp

If you run only
_application ("bo.Main"). start ();_
That answer will be _org.assertj.swing.exception.UnexpectedException: Unable to load class 'bo.Main'_

If first I run .jnlp myself to see the UI, then the result is the same.
_public static void start () {
         Desktop desktop = Desktop.getDesktop ();
         try {
             desktop.open (new File ("%some path%/file.jnlp"));
         } catch (IOException e) {
             e.printStackTrace ();
         }
     }_
