### ISSUE TITLE
Equivalent to Hamcrest hasProperty(String, Matcher) ?

### ISSUE THREAD

**Issue by ThrawnCA** [joel-costigliola/assertj-examples#46]
I like AssertJ's fluent syntax better than Hamcrest, but I'm having trouble finding an equivalent to the following Hamcrest pattern:

    assertThat(person, allOf(
        hasProperty("name", allOf(
            hasProperty("firstName", "John"),
            hasProperty("lastName", "Smith")
        )),
        hasProperty("address", allOf(
            hasProperty("streetNumber", 1),
            hasProperty("streetName", "Yellowbrick"),
            hasProperty("streetType", "Rd")
        )),
        hasProperty("dateOfBirth", "1970-01-01")
    ));

I can get part of the way with `extracting`, but then I can't make any more assertions on the original `person`, and the fluent syntax breaks down without any compile-time type information. I could probably do something by writing a bunch of custom `Condition` code, but I want this in more than one project, and I don't want to reinvent it. Am I missing something obvious?

**Comment by joel-costigliola** [comment]
You can give a try to [hasFieldOrPropertyWithValue](http://joel-costigliola.github.io/assertj/core-8/api/org/assertj/core/api/AbstractObjectAssert.html#hasFieldOrPropertyWithValue-java.lang.String-java.lang.Object-) which supports nested field notation like `name.firstName`.

Hope it helps.

**Comment by ThrawnCA** [comment]
Thanks for the tip. Yes, I did consider that at one point, and it will probably work.

When there's a long list of properties to be tested, though, surely there should be a more efficient method? It's not very DRY to have "person.name.address.xxx" over and over, whereas normally AssertJ is gratifyingly concise.

And what if a project needs to do more complex assertions on the properties than simple equality checks?

**Comment by joel-costigliola** [comment]
AssertJ does not support this approach (and there is no plan to mimic Hamcrest).
The idiomatic way would be to perform assertions by navigating to the field first, I mean something like:
```
assertThat(foo.getPets()).hasSize(1);
assertThat(foo.getPets().get(0).getName()).isEqualTo("fido");
assertThat(foo.getPets().get(0).getToys()).contains ... 
```
I do realize though this is probably not what you are looking for.

**Comment by ThrawnCA** [comment]
It's not ideal. I really like how fluent the AssertJ syntax usually is.

But thanks for clarifying.

**Comment by joel-costigliola** [comment]
Yeah, for combining assertions, Hamcrest is better than AssertJ.
I'm closing this issue since there won't be any work for it but feel free to continue commenting on it if you have more to say (I'll reopen it or create anotther issue if we find some improvements that can be addressed).

**Comment by ThrawnCA** [comment]
Hmm.

What if `AbstractObjectArrayAssert` could iterate through an assertion chain?

Eg:

    assertThat(person).extracting("name", "employer", "pets")
        .first().isEqualTo("John")
        .next()
        .hasFieldOrPropertyWithValue("organisationName", "MegaCorp")
        .hasFieldOrPropertyWithValue("address", "1 Bucks Rd")
        .next()
        .hasNoNullFieldsOrProperties()
        .extracting("name", "toys")
            .first().isEqualTo("Fido")
            .next()
            .extracting("value")
                .containsExactlyInAnyOrder("ball", "bone");

It wouldn't be as expressive as directly making assertions on each field, but it would be a step up from simple `AbstractObjectArrayAssert.contains` which can only do equality checks.

For better readability but more internal complexity, it could even be treated somewhat like a map instead of an iterator, with the asserts for each property being aware of each other and accessed by the keys used to extract them:

    assertThat(person).extractingLinkedAsserts("name", "employer", "pets")
        .assertThat("name").isEqualTo("John")
        .assertThat("employer")
            .hasFieldOrPropertyWithValue("organisationName", "MegaCorp")
            .hasFieldOrPropertyWithValue("address", "1 Bucks Rd")
        .assertThat("pets")
            .hasNoNullFieldsOrProperties()
            .extracting("name", "toys")
                .assertThat("name").isEqualTo("Fido")
                .assertThat("toys")
                    .extracting("value")
                        .containsExactlyInAnyOrder("ball", "bone");

**Comment by joel-costigliola** [comment]
That is worth spiking, we already have (limited) navigation support like [`element(i)`](http://joel-costigliola.github.io/assertj/core-8/api/org/assertj/core/api/AbstractIterableAssert.html#element-int-) but it  does not play well with strongly typed assertions (Java is limited for runtime type discovery) and is tricky to handle in soft assertions.

Feel free to create an issue in assertj-core so that we can spike it.

**Comment by ThrawnCA** [comment]
Huh. `element` does look useful. However, it's not available on `AbstractObjectArrayAssert`, which is what `extracting` returns. I think I'll raise an issue to add it, since accessing arrays by index is quite reasonable.

I don't think it would handle the chaining issue, though. You still end up with an assertion that only knows about the one object you selected, without being able to fluently navigate to others. But good point about soft assertions, they'd complicate things.
